name: User CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  ci_cd_common:
    uses: Sandeepkumar0088/azure-reusable-github-actions/.github/workflows/ci.yml@main
    with:
      component: user
      appType: nodejs
####